import Head from "next/head";
import React, { useRef } from "react";
import Dropdown from "./Dropdown";
import Navbar from "./Navbar";
import { useGlobalContext } from "../hooks/context";

const MobileLayout = ({ children }) => {
  const { dropdown, setDropdown } = useGlobalContext();
  const hamBurger = useRef();
  const showMenu = () => {
    setDropdown(!dropdown);
    hamBurger.current.classList.toggle("hamburger_active");
  };
  return (
    <>
      <Head>
        <title>emmatechy | Frontend developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-[#151515] min-h-screen text-white">
        <Navbar showMenu={showMenu} hamBurger={hamBurger} />
        {!dropdown ? <div>{children}</div> : <Dropdown showMenu={showMenu} />}
      </div>
    </>
  );
};

export default MobileLayout;
