import React from "react";
import Head from "next/head";
import { ApolloClient, InMemoryCache, gql } from "@apollo/client";
import ArticleContent from "../../components/ArticleContent";

export const getStaticPaths = async () => {
  const client = new ApolloClient({
    uri: "https://gql.hashnode.com/",
    cache: new InMemoryCache(),
  });

  const { data } = await client.query({
    query: gql`
      query GetUserArticles {
        publication(host: "emmanuel-eze.hashnode.dev") {
          posts(first: 10) {
            edges {
              node {
                id
                title
                slug
              }
            }
          }
        }
      }
    `,
  });

  const paths = data?.publication?.posts?.edges.map((post) => {
    return {
      params: { id: post?.node?.slug.toString() },
    };
  });
  return {
    paths: paths,
    fallback: false,
  };
};
export const getStaticProps = async (context) => {
  const id = context.params.id;
  try {
    const client = new ApolloClient({
      uri: "https://gql.hashnode.com/",
      cache: new InMemoryCache(),
    });

    const { data } = await client.query({
      query: gql`
        query GetUserById($id: String!) {
          publication(host: "emmanuel-eze.hashnode.dev") {
            post(slug: $id) {
              title
              slug
              publishedAt
              readTimeInMinutes
              content {
                markdown
              }
            }
          }
        }
      `,
      variables: {
        id: id,
      },
    });

    return {
      props: {
        post: data?.publication?.post,
      },
    };
  } catch (error) {
    return {
      props: {
        error: error.message,
      },
    };
  }
};

const article = ({ post }) => {
  return (
    <>
      <Head>
        <title>{post?.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/photo.ico" />
      </Head>
      {!post ? (
        <div className="text-white h-[90vh] grid place-items-center">
          Loading...
        </div>
      ) : (
        <div>
          <ArticleContent post={post} />
        </div>
      )}
    </>
  );
};

export default article;
