import Head from "next/head";
import Projects from "../components/Projects";
import Layout from "../layout/Layout";

export default function Home() {
  return (
    <>
      <Head>
        <title>emmatechy | Frontend developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/photo.ico" />
      </Head>
      <Layout home={true}>
        <Projects />
      </Layout>
    </>
  );
}
