import Head from "next/head";
import useWindowSize from "../hooks/useWindowSize";
import MobileHomeContent from "../components/MobileHomeContent";
import Projects from "../components/Projects";

export default function Home() {
  const windowSize = useWindowSize();
  return (
    <div>
      <Head>
        <title>emmatechy | Frontend developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {windowSize.width > 768 ? <Projects /> : <MobileHomeContent />}
    </div>
  );
}
