import Head from "next/head";
import MyResume from "../components/MyResume";
import Layout from "../layout/Layout";

const Resume = () => {
  return (
    <>
      <Head>
        <title>Frontend developer | Resume</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/photo.ico" />
      </Head>
      <Layout>
        <MyResume />
      </Layout>
    </>
  );
};

export default Resume;
