import Head from "next/head";
import Projects from "../components/Projects";
import Layout from "../layout/Layout";

const work = () => {
  return (
    <>
      <Head>
        <title>Frontend developer | Works</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/photo.ico" />
      </Head>
      <Layout>
        <Projects />
      </Layout>
    </>
  );
};

export default work;
